/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VIEW;

import CONTROLLER.CaminhaoController;
import CONTROLLER.CarroController;
import CONTROLLER.MotoController;
import SERVICES.Service;

import javax.swing.*;

/**
 *
 * @author jgabr
 */
public class RelatorioVeiculos extends javax.swing.JFrame {

    /** Creates new form relatorioVeiculos */
    public RelatorioVeiculos(int id) {
        idLogado = id;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbox1 = new java.awt.Checkbox();
        jLabel3 = new javax.swing.JLabel();
        arquivoTextField = new javax.swing.JTextField();
        filtroComboBox = new javax.swing.JComboBox<>();
        pesquisaTxt = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        exportar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        checkbox1.setLabel("checkbox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setText("Digite qual será o nome do arquivo:");

        arquivoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquivoTextFieldActionPerformed(evt);
            }
        });

        filtroComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modelo", "Marca", "Placa" }));
        filtroComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroComboBoxActionPerformed(evt);
            }
        });

        pesquisaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaTxtActionPerformed(evt);
            }
        });

        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        jLabel2.setText("Pesquisar por: ");

        exportar.setText("EXPORTAR PARA TXT");
        exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        area.setColumns(20);
        area.setRows(5);
        area.setAlignmentX(30.0F);
        area.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(area);

        jLabel4.setText("Selecione o tipo de veiculo:");

        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto", "Caminhão" }));
        tipoComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoComboBoxItemStateChanged(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("RELATÓRIO DE VEÍCULOS");

        jMenu1.setText("Cadastros");

        jMenuItem6.setText("Venda");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Funcionários");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu3.setText("Veículos");

        jMenuItem3.setText("Carro");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Moto");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Caminhão");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        jMenuItem7.setText("Clientes");
        jMenuItem7.setToolTipText("");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Funcionarios");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Veiculos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Vendas");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(arquivoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filtroComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(pesquisaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)))
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtroComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisar)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportar)
                    .addComponent(jLabel3)
                    .addComponent(arquivoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void arquivoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arquivoTextFieldActionPerformed

    private void filtroComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroComboBoxActionPerformed

    private void pesquisaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaTxtActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        // TODO add your handling code here:

        // verifica o tipo de veiculo e se o usuario é root, para chamar o metodo apropriado
        int filtro = filtroComboBox.getSelectedIndex();
        int tipo = tipoComboBox.getSelectedIndex();

        if(idLogado == 1){
            switch (tipo){
                case 0:
                    switch (filtro){

                        case 0:
                            System.out.println(filtro);
                            System.out.println(tipo);
                            area.setText(CarroController.relatorioPorModeloRoot(pesquisaTxt.getText()));
                            break;
                        case 1:
                            System.out.println(filtro);
                            System.out.println(tipo);
                            area.setText(CarroController.relatorioPorMarcaRoot(pesquisaTxt.getText()));
                            break;
                        case 2:
                            System.out.println(filtro);
                            System.out.println(tipo);
                            area.setText(CarroController.relatorioPorPlacaRoot(pesquisaTxt.getText()));
                            break;
                    }
                    break;
                case 1:
                    switch (filtro){
                        case 0:
                            System.out.println(filtro);
                            System.out.println(tipo);
                            area.setText(MotoController.relatorioPorModeloRoot(pesquisaTxt.getText()));
                            break;
                        case 1:
                            System.out.println(filtro);
                            System.out.println(tipo);
                            area.setText(MotoController.relatorioPorMarcaRoot(pesquisaTxt.getText()));
                            break;
                        case 2:
                            System.out.println(filtro);
                            System.out.println(tipo);
                            area.setText(MotoController.relatorioPorPlacaRoot(pesquisaTxt.getText()));
                            break;
                    }
                    break;
                case 2:
                    switch (filtro){
                        case 0:
                            System.out.println(filtro);
                            System.out.println(tipo);
                            area.setText(CaminhaoController.relatorioPorModeloRoot(pesquisaTxt.getText()));
                            break;
                        case 1:
                            System.out.println(filtro);
                            System.out.println(tipo);
                            area.setText(CaminhaoController.relatorioPorMarcaRoot(pesquisaTxt.getText()));
                            break;
                        case 2:
                            System.out.println(filtro);
                            System.out.println(tipo);
                            area.setText(CaminhaoController.relatorioPorPlacaRoot(pesquisaTxt.getText()));
                            break;
                    }
                    break;
            }
        }else {
            switch (tipo){
                case 0:
                    switch (filtro){
                        case 0:
                            area.setText(CarroController.relatorioPorModelo(pesquisaTxt.getText()));
                            break;
                        case 1:
                            area.setText(CarroController.relatorioPorMarca(pesquisaTxt.getText()));
                            break;
                        case 2:
                            area.setText(CarroController.relatorioPorPlaca(pesquisaTxt.getText()));
                            break;
                    }
                    break;
                case 1:
                    switch (filtro){
                        case 0:
                            area.setText(MotoController.relatorioPorModelo(pesquisaTxt.getText()));
                            break;
                        case 1:
                            area.setText(MotoController.relatorioPorMarca(pesquisaTxt.getText()));
                            break;
                        case 2:
                            area.setText(MotoController.relatorioPorPlaca(pesquisaTxt.getText()));
                            break;
                    }
                    break;
                case 2:
                    switch (filtro){
                        case 0:
                            area.setText(CaminhaoController.relatorioPorModelo(pesquisaTxt.getText()));
                            break;
                        case 1:
                            area.setText(CaminhaoController.relatorioPorMarca(pesquisaTxt.getText()));
                            break;
                        case 2:
                            area.setText(CaminhaoController.relatorioPorPlaca(pesquisaTxt.getText()));
                            break;
                    }
                    break;
            }

        }
        //
    }//GEN-LAST:event_pesquisarActionPerformed

    private void exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarActionPerformed
        // TODO add your handling code here:
        Service.exportaTxt(arquivoTextField.getText(),area.getText());
        JOptionPane.showMessageDialog(this,"O arquivo está disponivel em:\n" + "C:\\SaidaJava" ,"Arquivo exportado com sucesso",JOptionPane.INFORMATION_MESSAGE,null);
        arquivoTextField.setText("");
        //
    }//GEN-LAST:event_exportarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (idLogado == 1){
            area.setText(CarroController.relatorioGeralRoot());
        }else {
            area.setText(CarroController.relatorioGeral());
        }
    }//GEN-LAST:event_formWindowOpened

    private void tipoComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoComboBoxItemStateChanged
        // TODO add your handling code here:
        int tipo = tipoComboBox.getSelectedIndex();

        switch (tipo){
            case 0:
                if (idLogado == 1){
                    area.setText(CarroController.relatorioGeralRoot());
                }else {
                    area.setText(CarroController.relatorioGeral());

                }
                break;
            case 1:
                if (idLogado == 1){
                    area.setText(MotoController.relatorioGeralRoot());
                }else {
                    area.setText(MotoController.relatorioGeral());
                }
                break;
            case 2:
                if (idLogado == 1){
                    area.setText(CaminhaoController.relatorioGeralRoot());
                }else {
                    area.setText( CaminhaoController.relatorioGeral());
                }
                break;

        }
    }//GEN-LAST:event_tipoComboBoxItemStateChanged

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        CadastroVendas c = new CadastroVendas(idLogado);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        CadastroClientes c = new CadastroClientes(idLogado);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadastroFuncionarios c = new CadastroFuncionarios(idLogado);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        CadastroCarros c = new CadastroCarros(idLogado);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        CadastroMotos c = new CadastroMotos(idLogado);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        CadastroCaminhoes c = new CadastroCaminhoes(idLogado);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        RelatorioClientes c = new RelatorioClientes(idLogado);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        RelatorioFuncionarios c = new RelatorioFuncionarios(idLogado);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        RelatorioVeiculos c = new RelatorioVeiculos(idLogado);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        RelatorioVendas c = new RelatorioVendas(idLogado);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem10ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JTextField arquivoTextField;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JButton exportar;
    private javax.swing.JComboBox<String> filtroComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pesquisaTxt;
    private javax.swing.JButton pesquisar;
    public javax.swing.JComboBox<String> tipoComboBox;
    // End of variables declaration//GEN-END:variables
    private int idLogado;

}
